### PR TITLE
Fix proposal for #26

### PR DESCRIPTION
**Pull request by Aurelien30000**
Fix of https://github.com/Nathat23/StackMob-5/issues/26

- Tested and working, issue never occurs anymore...
- Other tries are appreciate, test build here https://ci.ecocitycraft.com/job/StackMob-5.1-Aurelien30000/ :)

### CODE REVIEW

**Comment by Nathat23** [comment]
I've finally found a way to replicate the issue (using MythicMobs) and while this does fix the error if the custom health is lower than the default vanilla health, it does not fix it if the custom health is higher than that of the vanilla heath.

**Comment by Aurelien30000** [comment]
Should we change the max health of the ne entity 🤔

**Comment by Aurelien30000** [comment]
And could you describe more precisely the issue with MythicMobs, what do you mean by custom health and Vanilla health 🤔 Is it the same stacktrace / error ? :)

**Comment by Nathat23** [comment]
> And could you describe more precisely the issue with MythicMobs, what do you mean by custom health and Vanilla health thinking Is it the same stacktrace / error ? :)

The custom health is the health set in the VanillaMobs.yml file, different from what would it would be normally.

**Comment by Aurelien30000** [comment]
New build will be available soon -> https://ci.ecocitycraft.com/job/StackMob-5.1-Aurelien30000/
I tried a fix to solve issue with MythicMobs' custom max health, thanks for the report !

**Comment by Nathat23** [comment]
From my testing, I'm pretty sure that MythicMobs sets the max health attribute after the entity has spawned, which is why the error occurs. Maybe a solution would be to delay setting health with a task?

**Comment by Aurelien30000** [comment]
Wait is unsafe I think, delay could vary and bring issues 🤔 We should rather use event priority if listener in MythicMobs haven't HIGHEST priority.

**Comment by Aurelien30000** [comment]
Hum, I'm not actually sure of that, the entity is spawned before onSpawn() method is called.

**Comment by Aurelien30000** [comment]
Let's try a wait anyway.

**Comment by Aurelien30000** [comment]
New build will be available soon -> https://ci.ecocitycraft.com/job/StackMob-5.1-Aurelien30000/

**Comment by Aurelien30000** [comment]
Hum, let's think a bit...
If an entity has a different max health than the vanilla default behaviour, what should be the possible reasons ?

- Health boost effect

-> Potion effects are not (now) traits to compare entities, they are merged no matter their effects. So the new entity should have the default max health or not ? Don't forget that an effect is temporary and specific to one entity without a trait.

- Custom entity or modification by a plugin

-> Like MythicsMobs, plugin do the job itself, I think, just need to implement the hook to wait health setting.

I don't see any other reason to this issue personnaly, don't hesitate to participate to the discussion and give your opinion, in order to provide the best fix for all cases :) Thanks !

**Pull request closed without merging**
